# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 828d60a2a6653e13a9b202ae4d021bfddef65c198a1c733f3b1c9e0e90bab11333693fbd610f44dc6982a66b5a1a6fd29022b5c9afa8520d20c02fbb0e7c1fcb

test:
  secret_key_base: 698b38c5983ab8ed0f8a95658e061bfb580a5c6e8704f28e2f3334fea12198c99f96f91408524f28b4212ca54d3a1a83a25e40a63e8b105524eed428776e26cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
